apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rawkode
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: ko://github.com/mattmoor/rawkode-klusterfuck/cmd/webhook 
